### ISSUE TITLE
About exiftool name

### ISSUE THREAD

**Issue by matrixik** [evanoberholster/image-meta#4]
Hello,

on https://discuss.pixls.us/t/looking-for-sample-raw-photos-from-many-camera-manufacturers-for-testing-exif-extraction/18833/7?u=matrixik
there is actually good comment about this library name. It's the same as exiftool.org (that you even link in README).

Going forward problem with this name could be that it's confusing to users, if you create cmd tool using this name when installed it will clash with exiftool.org version (because of the same name), impossible to find your library/tool in Google/any other search engine because all links will be referring to exiftool.org tool (because it's a lot older and have wide usage) and probably more I'm not thinking now.

**Comment by evanoberholster** [comment]
@matrixik Thanks for the issue, I agree it's extremely misleading and can definitely cause confusion. I wasn't very creative when choosing this name. The goal of this library is a minimalist, performance focused library in pure go that supports reading exif from image files. I will work on renaming the library, any suggestions?

**Comment by matrixik** [comment]
When I search for name for my tool most of the time when I think about something I'm doing google search to check if this name have any direct/strong user. For example for `imagemeta` I can see there is https://imagemeta.io/ service using it and it appear first places on google search. `imgmeta` also have at least 3 tools using it.

I was thinking some time about it (because I'm bad at thinking new names :P ) and maybe something like `camexif` or `phexif` (from joining camera/photo with exif) would be acceptable for you? At least if you want this library to be focused on camera photos data processing.

This are not hard recommendations, just use what you like and don't have many results on search engines.

**Comment by evanoberholster** [comment]
@matrixik Thank you for your suggestions of camexif and phexif. The scope of this library is more about the images than cameras. I have searched online of the name imageexif and haven't seen any conflicts. Would you consider this a good name?

**Comment by evanoberholster** [comment]
@matrixik I finally renamed the package to image-meta. I know that there are similar packages but the scope includes more metadata than just exif.
